image: node:10.15.3

stages:
  - install_dependencies
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm i
  only:
    changes:
      - package.json
      

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/


deploy as review app:
  image: rambabusaravanan/firebase
  stage: deploy
  environment:
    name: review
    url: https://waza-membership.web.app
  only:
    - develop
    - master
  script:
    - firebase use waza-membership --token $FIREBASE_TOKEN
    - firebase target:apply hosting passenger waza-membership
    - firebase deploy --only hosting -m "Commit $CI_COMMIT_TITLE Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
